# Generated by Django 4.2.29 on 2026-04-01 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tender',
            options={'ordering': ['-closing_date']},
        ),
        migrations.RemoveField(
            model_name='tender',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='tender',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tender',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='closing_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='department',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tender',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='source',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tender_id',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['category', 'location'], name='tenders_ten_categor_f90a25_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['source', 'closing_date'], name='tenders_ten_source_975aef_idx'),
        ),
    ]
