# Generated by Django 4.2.29 on 2026-04-02 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_alter_tender_options_remove_tender_publish_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True, default='')),
                ('summary_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='tenders.tender')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
