# Generated by Django 4.2.29 on 2026-04-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_tenderdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='department',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='link',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tender',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
    ]
