# Generated by Django 4.2.29 on 2026-04-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_alter_tender_department_alter_tender_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenderdocument',
            old_name='raw_text',
            new_name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='tenderdocument',
            name='tender',
        ),
        migrations.AddField(
            model_name='tenderdocument',
            name='file',
            field=models.FileField(default='', upload_to='tender_pdfs/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tender',
        ),
    ]
