# Generated by Django 4.2.29 on 2026-05-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0005_rename_raw_text_tenderdocument_extracted_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderdocument',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenderdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting Text'), ('analyzing', 'AI Analysis'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
